name: Run Noisy

on: [pull_request, push]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: pip

    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
    - name: Run Noisy
      run: |
        python3 noisy.py --timeout 60

    - name: Install tested dependencies
      run: |
        pip3 install -r requirements_tested.txt
    - name: Run Noisy with tested dependencies
      run: |
        python3 noisy.py --timeout 60